version: '3'
services:
  aggregator:
    build:
      context: .
      dockerfile: aggregator/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - YAHOO_FINANCE_API_URL=https://query1.finance.yahoo.com
      - PORT=8080
    volumes:
      - ./aggregator/data:/app/aggregator/data