// api/proto/portfolio_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: portfolio_service.proto

package portfolio_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PortfolioService_WeeklyRebalance_FullMethodName    = "/portfolioservice.PortfolioService/WeeklyRebalance"
	PortfolioService_BiWeeklyRebalance_FullMethodName  = "/portfolioservice.PortfolioService/BiWeeklyRebalance"
	PortfolioService_GetPortfolioStatus_FullMethodName = "/portfolioservice.PortfolioService/GetPortfolioStatus"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	WeeklyRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*PortfolioUpdate, error)
	BiWeeklyRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*PortfolioUpdate, error)
	GetPortfolioStatus(ctx context.Context, in *PortfolioStatusRequest, opts ...grpc.CallOption) (*PortfolioStatus, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) WeeklyRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*PortfolioUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioUpdate)
	err := c.cc.Invoke(ctx, PortfolioService_WeeklyRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) BiWeeklyRebalance(ctx context.Context, in *RebalanceRequest, opts ...grpc.CallOption) (*PortfolioUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioUpdate)
	err := c.cc.Invoke(ctx, PortfolioService_BiWeeklyRebalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetPortfolioStatus(ctx context.Context, in *PortfolioStatusRequest, opts ...grpc.CallOption) (*PortfolioStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioStatus)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolioStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility
type PortfolioServiceServer interface {
	WeeklyRebalance(context.Context, *RebalanceRequest) (*PortfolioUpdate, error)
	BiWeeklyRebalance(context.Context, *RebalanceRequest) (*PortfolioUpdate, error)
	GetPortfolioStatus(context.Context, *PortfolioStatusRequest) (*PortfolioStatus, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortfolioServiceServer struct {
}

func (UnimplementedPortfolioServiceServer) WeeklyRebalance(context.Context, *RebalanceRequest) (*PortfolioUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WeeklyRebalance not implemented")
}
func (UnimplementedPortfolioServiceServer) BiWeeklyRebalance(context.Context, *RebalanceRequest) (*PortfolioUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BiWeeklyRebalance not implemented")
}
func (UnimplementedPortfolioServiceServer) GetPortfolioStatus(context.Context, *PortfolioStatusRequest) (*PortfolioStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolioStatus not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_WeeklyRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).WeeklyRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_WeeklyRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).WeeklyRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_BiWeeklyRebalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).BiWeeklyRebalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_BiWeeklyRebalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).BiWeeklyRebalance(ctx, req.(*RebalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetPortfolioStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolioStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolioStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolioStatus(ctx, req.(*PortfolioStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portfolioservice.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WeeklyRebalance",
			Handler:    _PortfolioService_WeeklyRebalance_Handler,
		},
		{
			MethodName: "BiWeeklyRebalance",
			Handler:    _PortfolioService_BiWeeklyRebalance_Handler,
		},
		{
			MethodName: "GetPortfolioStatus",
			Handler:    _PortfolioService_GetPortfolioStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portfolio_service.proto",
}
