// api/proto/trade_execution_service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: trade_execution_service.proto

package trade_execution_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TradeExecutionService_ExecuteTrade_FullMethodName       = "/tradeexecutionservice.TradeExecutionService/ExecuteTrade"
	TradeExecutionService_GetExecutionStatus_FullMethodName = "/tradeexecutionservice.TradeExecutionService/GetExecutionStatus"
)

// TradeExecutionServiceClient is the client API for TradeExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeExecutionServiceClient interface {
	ExecuteTrade(ctx context.Context, in *TradeOrder, opts ...grpc.CallOption) (*TradeResult, error)
	GetExecutionStatus(ctx context.Context, in *ExecutionStatusRequest, opts ...grpc.CallOption) (*TradeResult, error)
}

type tradeExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeExecutionServiceClient(cc grpc.ClientConnInterface) TradeExecutionServiceClient {
	return &tradeExecutionServiceClient{cc}
}

func (c *tradeExecutionServiceClient) ExecuteTrade(ctx context.Context, in *TradeOrder, opts ...grpc.CallOption) (*TradeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, TradeExecutionService_ExecuteTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeExecutionServiceClient) GetExecutionStatus(ctx context.Context, in *ExecutionStatusRequest, opts ...grpc.CallOption) (*TradeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeResult)
	err := c.cc.Invoke(ctx, TradeExecutionService_GetExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeExecutionServiceServer is the server API for TradeExecutionService service.
// All implementations must embed UnimplementedTradeExecutionServiceServer
// for forward compatibility
type TradeExecutionServiceServer interface {
	ExecuteTrade(context.Context, *TradeOrder) (*TradeResult, error)
	GetExecutionStatus(context.Context, *ExecutionStatusRequest) (*TradeResult, error)
	mustEmbedUnimplementedTradeExecutionServiceServer()
}

// UnimplementedTradeExecutionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTradeExecutionServiceServer struct {
}

func (UnimplementedTradeExecutionServiceServer) ExecuteTrade(context.Context, *TradeOrder) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTrade not implemented")
}
func (UnimplementedTradeExecutionServiceServer) GetExecutionStatus(context.Context, *ExecutionStatusRequest) (*TradeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionStatus not implemented")
}
func (UnimplementedTradeExecutionServiceServer) mustEmbedUnimplementedTradeExecutionServiceServer() {}

// UnsafeTradeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeExecutionServiceServer will
// result in compilation errors.
type UnsafeTradeExecutionServiceServer interface {
	mustEmbedUnimplementedTradeExecutionServiceServer()
}

func RegisterTradeExecutionServiceServer(s grpc.ServiceRegistrar, srv TradeExecutionServiceServer) {
	s.RegisterService(&TradeExecutionService_ServiceDesc, srv)
}

func _TradeExecutionService_ExecuteTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeExecutionServiceServer).ExecuteTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeExecutionService_ExecuteTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeExecutionServiceServer).ExecuteTrade(ctx, req.(*TradeOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeExecutionService_GetExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeExecutionServiceServer).GetExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeExecutionService_GetExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeExecutionServiceServer).GetExecutionStatus(ctx, req.(*ExecutionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeExecutionService_ServiceDesc is the grpc.ServiceDesc for TradeExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradeexecutionservice.TradeExecutionService",
	HandlerType: (*TradeExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTrade",
			Handler:    _TradeExecutionService_ExecuteTrade_Handler,
		},
		{
			MethodName: "GetExecutionStatus",
			Handler:    _TradeExecutionService_GetExecutionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_execution_service.proto",
}
