// api/proto/strategy_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: strategy_service.proto

package strategy_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalType int32

const (
	SignalType_HOLD SignalType = 0
	SignalType_BUY  SignalType = 1
	SignalType_SELL SignalType = 2
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0: "HOLD",
		1: "BUY",
		2: "SELL",
	}
	SignalType_value = map[string]int32{
		"HOLD": 0,
		"BUY":  1,
		"SELL": 2,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_strategy_service_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_strategy_service_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_strategy_service_proto_rawDescGZIP(), []int{0}
}

type SignalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_strategy_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signals                []*StockSignal `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	IsMarketRegimePositive bool           `protobuf:"varint,2,opt,name=is_market_regime_positive,json=isMarketRegimePositive,proto3" json:"is_market_regime_positive,omitempty"`
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_strategy_service_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetSignals() []*StockSignal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *SignalResponse) GetIsMarketRegimePositive() bool {
	if x != nil {
		return x.IsMarketRegimePositive
	}
	return false
}

type StockSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol       string     `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Signal       SignalType `protobuf:"varint,2,opt,name=signal,proto3,enum=strategyservice.SignalType" json:"signal,omitempty"`
	PositionSize float64    `protobuf:"fixed64,3,opt,name=position_size,json=positionSize,proto3" json:"position_size,omitempty"`
}

func (x *StockSignal) Reset() {
	*x = StockSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockSignal) ProtoMessage() {}

func (x *StockSignal) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockSignal.ProtoReflect.Descriptor instead.
func (*StockSignal) Descriptor() ([]byte, []int) {
	return file_strategy_service_proto_rawDescGZIP(), []int{2}
}

func (x *StockSignal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockSignal) GetSignal() SignalType {
	if x != nil {
		return x.Signal
	}
	return SignalType_HOLD
}

func (x *StockSignal) GetPositionSize() float64 {
	if x != nil {
		return x.PositionSize
	}
	return 0
}

var File_strategy_service_proto protoreflect.FileDescriptor

var file_strategy_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x83,
	0x01, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x12, 0x39, 0x0a, 0x19, 0x69, 0x73, 0x5f,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x69, 0x73,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6d, 0x65, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x22, 0x7f, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x33, 0x0a, 0x06, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x69, 0x7a, 0x65, 0x2a, 0x29, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x4c, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x42, 0x55, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x02,
	0x32, 0x69, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x12, 0x1e, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x6d,
	0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x2d, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x2d,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategy_service_proto_rawDescOnce sync.Once
	file_strategy_service_proto_rawDescData = file_strategy_service_proto_rawDesc
)

func file_strategy_service_proto_rawDescGZIP() []byte {
	file_strategy_service_proto_rawDescOnce.Do(func() {
		file_strategy_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategy_service_proto_rawDescData)
	})
	return file_strategy_service_proto_rawDescData
}

var file_strategy_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_strategy_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_strategy_service_proto_goTypes = []any{
	(SignalType)(0),        // 0: strategyservice.SignalType
	(*SignalRequest)(nil),  // 1: strategyservice.SignalRequest
	(*SignalResponse)(nil), // 2: strategyservice.SignalResponse
	(*StockSignal)(nil),    // 3: strategyservice.StockSignal
}
var file_strategy_service_proto_depIdxs = []int32{
	3, // 0: strategyservice.SignalResponse.signals:type_name -> strategyservice.StockSignal
	0, // 1: strategyservice.StockSignal.signal:type_name -> strategyservice.SignalType
	1, // 2: strategyservice.StrategyService.GetTradingSignals:input_type -> strategyservice.SignalRequest
	2, // 3: strategyservice.StrategyService.GetTradingSignals:output_type -> strategyservice.SignalResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_strategy_service_proto_init() }
func file_strategy_service_proto_init() {
	if File_strategy_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strategy_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SignalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SignalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StockSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategy_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_service_proto_goTypes,
		DependencyIndexes: file_strategy_service_proto_depIdxs,
		EnumInfos:         file_strategy_service_proto_enumTypes,
		MessageInfos:      file_strategy_service_proto_msgTypes,
	}.Build()
	File_strategy_service_proto = out.File
	file_strategy_service_proto_rawDesc = nil
	file_strategy_service_proto_goTypes = nil
	file_strategy_service_proto_depIdxs = nil
}
